<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>McpLense.IntegrationTests</AssemblyName>
    <RootNamespace>McpLense.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\McpLense\McpLense.csproj" />
    <ProjectReference Include="..\..\src\McpLense.Cli\McpLense.Cli.csproj" />
    <ProjectReference Include="..\McpLense.TestServer\McpLense.TestServer.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
    <ProjectReference Include="..\McpLense.TestHttpServer\McpLense.TestHttpServer.csproj" />
    <ProjectReference Include="..\McpLense.TestMcps\McpLense.TestMcps.csproj" />
  </ItemGroup>

</Project>
